#!/usr/bin/env python

from __future__ import print_function
import argparse
import os
import sys

from alpine_pkg.project_version import bump_version
from alpine_pkg.projects import find_projects, verify_equal_project_versions

# find the import relatively if available to work before installing alpine or overlaying installed version
if os.path.exists(os.path.join(os.path.dirname(__file__), '..', 'python', 'alpine', '__init__.py')):
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'python'))
from alpine.project_version import update_versions


def main():
    parser = argparse.ArgumentParser(description='Show or bump the version number in project.xml files.')
    parser.add_argument('path', nargs='?', default='.', help='The path to a parent folder which contains project.xml files (default: .)')
    parser.add_argument('--bump', choices=('major', 'minor', 'patch'), help='Which part of the version number to bump?')
    args = parser.parse_args()

    try:
        projects = find_projects(args.path)
        if not projects:
            print('No project found', file=sys.stderr)
            sys.exit(1)
        version = verify_equal_project_versions(projects.values())

        # only print the version number
        if args.bump is None:
            print(version)

        else:
            # bump the version number
            new_version = bump_version(version, args.bump)
            update_versions(projects.keys(), new_version)
            print('%s -> %s' % (version, new_version))
    except Exception as e:
        sys.exit(str(e))

if __name__ == '__main__':
    main()
