#!/usr/bin/env python

"""This script finds a alpine projects"""

from __future__ import print_function
import argparse
import os
import sys

from alpine_pkg.projects import find_projects


def main(argv=sys.argv[1:]):
    parser = argparse.ArgumentParser(description='Find a alpine project')
    parser.add_argument('pkg', help='The name of the project')
    parser.add_argument('base_path', nargs='?', default=os.curdir, help='The base path to crawl for projects')

    args = parser.parse_args(argv)

    try:
        projects = find_projects(args.base_path)
        alpine_pkg = [path for path, p in projects.items() if p.name == args.pkg]
        if alpine_pkg:
            print(alpine_pkg[0])
        else:
            print("Could not find project '%s'." % args.pkg, file=sys.stderr)
            sys.exit(2)
    except RuntimeError as e:
        sys.exit(str(e))


if __name__ == '__main__':
    main()
